# Generated by Django 4.2.7 on 2025-05-28 12:32

import datetime
import django.core.validators
from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_doctor_first_name_doctor_info_doctor_last_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="age",
        ),
        migrations.AddField(
            model_name="client",
            name="date_of_birth",
            field=models.DateField(
                default=datetime.date(2001, 5, 17),
                validators=[myapp.models.validate_age],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="client",
            name="mobile",
            field=models.CharField(
                help_text="Введите номер в формате +375XXXXXXXXX без пробелов.",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(regex="^\\+375\\d{9}$")
                ],
            ),
        ),
    ]
