# Generated by Django 4.2.7 on 2025-05-28 12:56

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_remove_client_age_client_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="date_of_birth",
            field=models.DateField(
                blank=True, null=True, validators=[myapp.models.validate_age]
            ),
        ),
    ]
