# Generated by Django 4.2.7 on 2025-05-28 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_alter_client_date_of_birth"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="myapp.doctorcategory",
            ),
        ),
    ]
