# Generated by Django 4.2.7 on 2025-05-28 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_service_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialization",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="specializations",
                to="myapp.department",
            ),
        ),
    ]
