# Generated by Django 4.2.7 on 2025-05-28 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_specialization_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="plannedvisit",
            name="diagnosis_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
